SET IDENTITY_INSERT [dbo].[Item] ON
INSERT INTO [dbo].[Item] ([Id], [Type], [Name], [Price]) VALUES (1, 0, N'Cheeseburger', 17)
INSERT INTO [dbo].[Item] ([Id], [Type], [Name], [Price]) VALUES (2, 0, N'Bacon Cheeseburger', 19)
INSERT INTO [dbo].[Item] ([Id], [Type], [Name], [Price]) VALUES (3, 0, N'Barbecue Burger', 16)
INSERT INTO [dbo].[Item] ([Id], [Type], [Name], [Price]) VALUES (4, 0, N'California Burger', 16.5)
INSERT INTO [dbo].[Item] ([Id], [Type], [Name], [Price]) VALUES (5, 0, N'Hawaii Burger', 17)
INSERT INTO [dbo].[Item] ([Id], [Type], [Name], [Price]) VALUES (6, 0, N'Buffalo Burger', 13)
INSERT INTO [dbo].[Item] ([Id], [Type], [Name], [Price]) VALUES (7, 1, N'Iced Tea', 3)
INSERT INTO [dbo].[Item] ([Id], [Type], [Name], [Price]) VALUES (8, 1, N'Caramel Fudge Milkshake', 6)
INSERT INTO [dbo].[Item] ([Id], [Type], [Name], [Price]) VALUES (9, 1, N'Fanta', 4)
INSERT INTO [dbo].[Item] ([Id], [Type], [Name], [Price]) VALUES (10, 1, N'Sprite', 4)
INSERT INTO [dbo].[Item] ([Id], [Type], [Name], [Price]) VALUES (11, 1, N'Coca Cola', 4)
INSERT INTO [dbo].[Item] ([Id], [Type], [Name], [Price]) VALUES (12, 1, N'Coca Cola Zero', 4)
INSERT INTO [dbo].[Item] ([Id], [Type], [Name], [Price]) VALUES (14, 0, N'Mexican Burger', 17.5)
INSERT INTO [dbo].[Item] ([Id], [Type], [Name], [Price]) VALUES (15, 0, N'Italian Burger', 16.5)
INSERT INTO [dbo].[Item] ([Id], [Type], [Name], [Price]) VALUES (16, 0, N'Austrian Burger', 18)
INSERT INTO [dbo].[Item] ([Id], [Type], [Name], [Price]) VALUES (17, 0, N'French Burger', 17)
INSERT INTO [dbo].[Item] ([Id], [Type], [Name], [Price]) VALUES (18, 0, N'Thai Burger', 15.5)
INSERT INTO [dbo].[Item] ([Id], [Type], [Name], [Price]) VALUES (19, 1, N'Red Cherry Milkshake', 5)
INSERT INTO [dbo].[Item] ([Id], [Type], [Name], [Price]) VALUES (20, 1, N'Cappuccino Milkshake', 5)
INSERT INTO [dbo].[Item] ([Id], [Type], [Name], [Price]) VALUES (21, 1, N'Heineken', 7)
INSERT INTO [dbo].[Item] ([Id], [Type], [Name], [Price]) VALUES (22, 1, N'Carlsberg', 7)
INSERT INTO [dbo].[Item] ([Id], [Type], [Name], [Price]) VALUES (23, 0, N'Chili Burger', 16.5)
SET IDENTITY_INSERT [dbo].[Item] OFF