SET IDENTITY_INSERT [dbo].[Branch] ON
INSERT INTO [dbo].[Branch] ([Id], [Address], [City], [District]) VALUES (1, N'HaBanaim St 4', 0, 1)
INSERT INTO [dbo].[Branch] ([Id], [Address], [City], [District]) VALUES (2, N'Globus Center', 1, 1)
INSERT INTO [dbo].[Branch] ([Id], [Address], [City], [District]) VALUES (3, N'Moshe Beker St 9', 19, 2)
INSERT INTO [dbo].[Branch] ([Id], [Address], [City], [District]) VALUES (4, N'HaBarzel St 19', 20, 2)
INSERT INTO [dbo].[Branch] ([Id], [Address], [City], [District]) VALUES (5, N'Moriah Ave 110', 6, 0)
INSERT INTO [dbo].[Branch] ([Id], [Address], [City], [District]) VALUES (6, N'Heil Handasa St 1', 3, 1)
INSERT INTO [dbo].[Branch] ([Id], [Address], [City], [District]) VALUES (7, N'Shaul HaMelech St 80', 3, 1)
INSERT INTO [dbo].[Branch] ([Id], [Address], [City], [District]) VALUES (8, N'Tarshish St 19', 4, 1)
INSERT INTO [dbo].[Branch] ([Id], [Address], [City], [District]) VALUES (9, N'Elie Wiesel St 2', 19, 2)
INSERT INTO [dbo].[Branch] ([Id], [Address], [City], [District]) VALUES (10, N'Herzl St 8', 20, 2)
INSERT INTO [dbo].[Branch] ([Id], [Address], [City], [District]) VALUES (11, N'Sderot Achi Eilat 60', 6, 0)
INSERT INTO [dbo].[Branch] ([Id], [Address], [City], [District]) VALUES (16, N'Dizengoff St 166', 20, 2)
INSERT INTO [dbo].[Branch] ([Id], [Address], [City], [District]) VALUES (17, N'Arieh Shenkar St 11', 7, 2)
INSERT INTO [dbo].[Branch] ([Id], [Address], [City], [District]) VALUES (18, N'Atir Yeda St 1', 11, 2)
INSERT INTO [dbo].[Branch] ([Id], [Address], [City], [District]) VALUES (19, N'HaMada St 6', 18, 2)
INSERT INTO [dbo].[Branch] ([Id], [Address], [City], [District]) VALUES (20, N'HaShalom Rd 53', 5, 2)
INSERT INTO [dbo].[Branch] ([Id], [Address], [City], [District]) VALUES (21, N'Abba Eban Blvd 12', 7, 2)
INSERT INTO [dbo].[Branch] ([Id], [Address], [City], [District]) VALUES (22, N'King George St 41', 10, 2)
INSERT INTO [dbo].[Branch] ([Id], [Address], [City], [District]) VALUES (23, N'King David St 23', 10, 2)
INSERT INTO [dbo].[Branch] ([Id], [Address], [City], [District]) VALUES (24, N'Shacham St 17', 14, 2)
INSERT INTO [dbo].[Branch] ([Id], [Address], [City], [District]) VALUES (25, N'demo', 0, 0)
SET IDENTITY_INSERT [dbo].[Branch] OFF